/**
 * 五关剧本。时间单位是秒，0 是起跑瞬间。
 * 往下加关时照着追加一项：速度略增、时长落在 60 到 90 秒、正好 3 颗星。
 * 星星的 t 是它自己的位置。lift 为 0 表示贴地，越大越靠近跳跃顶点。
 * 尖刺的 t 是这一串最左边出现的时间。
 */
export const LEVEL_DEFS = [
  {
    id: 'level-1',
    name: '紫色冲刺',
    speed: 300,
    duration: 76,
    palette: 0,
    script: [
      { t: 1.6, type: 'star', lift: 0 },
      { t: 3.8, type: 'spike', count: 1 },
      { t: 7.2, type: 'spike', count: 1 },
      { t: 10.4, type: 'spike', count: 2 },
      { t: 10.55, type: 'star', lift: 78 },
      { t: 13.8, type: 'block' },
      { t: 17.2, type: 'checkpoint' },
      { t: 20.4, type: 'spike', count: 1 },
      { t: 23.8, type: 'overhead' },
      { t: 27.2, type: 'spike', count: 2 },
      { t: 30.8, type: 'block' },
      { t: 34.2, type: 'checkpoint' },
      { t: 37.4, type: 'spike', count: 1 },
      { t: 40.8, type: 'spike', count: 2 },
      { t: 44.2, type: 'overhead' },
      { t: 47.6, type: 'block' },
      { t: 51.0, type: 'checkpoint' },
      { t: 54.2, type: 'spike', count: 2 },
      { t: 57.8, type: 'spike', count: 1 },
      { t: 61.2, type: 'block' },
      { t: 64.6, type: 'spike', count: 3 },
      { t: 64.85, type: 'star', lift: 128 },
      { t: 68.4, type: 'checkpoint' },
      { t: 71.2, type: 'spike', count: 1 },
    ],
  },
  {
    id: 'level-2',
    name: '紫晶连跳',
    speed: 312,
    duration: 74,
    palette: 1,
    script: [
      { t: 1.5, type: 'star', lift: 0 },
      { t: 3.6, type: 'spike', count: 2 },
      { t: 6.0, type: 'spike', count: 2 },
      { t: 8.4, type: 'block' },
      { t: 10.6, type: 'spike', count: 1 },
      { t: 13.0, type: 'spike', count: 3 },
      { t: 13.25, type: 'star', lift: 96 },
      { t: 16.0, type: 'overhead' },
      { t: 18.6, type: 'checkpoint' },
      { t: 21.4, type: 'spike', count: 1 },
      { t: 22.7, type: 'spike', count: 2 },
      { t: 24.0, type: 'spike', count: 1 },
      { t: 25.3, type: 'block' },
      { t: 26.7, type: 'spike', count: 2 },
      { t: 29.4, type: 'checkpoint' },
      { t: 32.2, type: 'spike', count: 2 },
      { t: 34.6, type: 'overhead' },
      { t: 35.45, type: 'spike', count: 2 },
      { t: 37.8, type: 'block' },
      { t: 40.2, type: 'spike', count: 3 },
      { t: 40.45, type: 'star', lift: 140 },
      { t: 43.2, type: 'checkpoint' },
      { t: 46.0, type: 'block' },
      { t: 47.4, type: 'spike', count: 2 },
      { t: 49.6, type: 'spike', count: 2 },
      { t: 52.0, type: 'overhead' },
      { t: 54.6, type: 'spike', count: 3 },
      { t: 57.2, type: 'block' },
      { t: 59.8, type: 'checkpoint' },
      { t: 62.6, type: 'spike', count: 2 },
      { t: 64.8, type: 'spike', count: 1 },
      { t: 67.2, type: 'block' },
      { t: 69.6, type: 'spike', count: 2 },
    ],
  },
  {
    id: 'level-3',
    name: '靛色窄缝',
    speed: 324,
    duration: 72,
    palette: 2,
    script: [
      { t: 1.5, type: 'star', lift: 0 },
      { t: 3.5, type: 'spike', count: 2 },
      { t: 5.6, type: 'overhead' },
      { t: 6.35, type: 'spike', count: 2 },
      { t: 7.7, type: 'spike', count: 1 },
      { t: 9.2, type: 'block' },
      { t: 10.6, type: 'spike', count: 2 },
      { t: 12.4, type: 'spike', count: 3 },
      { t: 12.6, type: 'star', lift: 108 },
      { t: 15.2, type: 'checkpoint' },
      { t: 17.8, type: 'spike', count: 2 },
      { t: 19.05, type: 'spike', count: 2 },
      { t: 20.3, type: 'spike', count: 1 },
      { t: 21.55, type: 'spike', count: 2 },
      { t: 23.1, type: 'overhead' },
      { t: 23.85, type: 'spike', count: 3 },
      { t: 26.4, type: 'checkpoint' },
      { t: 29.0, type: 'block' },
      { t: 30.3, type: 'spike', count: 2 },
      { t: 31.6, type: 'block' },
      { t: 32.9, type: 'spike', count: 2 },
      { t: 34.4, type: 'overhead' },
      { t: 35.15, type: 'spike', count: 2 },
      { t: 36.6, type: 'spike', count: 1 },
      { t: 38.2, type: 'spike', count: 3 },
      { t: 38.55, type: 'star', lift: 46 },
      { t: 41.0, type: 'checkpoint' },
      { t: 43.6, type: 'spike', count: 2 },
      { t: 44.85, type: 'spike', count: 2 },
      { t: 46.1, type: 'spike', count: 2 },
      { t: 47.6, type: 'block' },
      { t: 49.0, type: 'overhead' },
      { t: 49.75, type: 'spike', count: 2 },
      { t: 51.4, type: 'spike', count: 3 },
      { t: 53.6, type: 'checkpoint' },
      { t: 56.2, type: 'block' },
      { t: 57.5, type: 'spike', count: 2 },
      { t: 58.9, type: 'overhead' },
      { t: 59.6, type: 'spike', count: 2 },
      { t: 61.1, type: 'block' },
      { t: 62.5, type: 'spike', count: 3 },
      { t: 64.8, type: 'checkpoint' },
      { t: 67.4, type: 'spike', count: 2 },
      { t: 68.8, type: 'spike', count: 1 },
    ],
  },
  {
    id: 'level-4',
    name: '玫红平台',
    speed: 336,
    duration: 70,
    palette: 3,
    script: [
      { t: 1.45, type: 'star', lift: 0 },
      { t: 3.3, type: 'block' },
      { t: 4.5, type: 'spike', count: 3 },
      { t: 5.9, type: 'block' },
      { t: 7.1, type: 'spike', count: 2 },
      { t: 8.5, type: 'overhead' },
      { t: 9.2, type: 'spike', count: 3 },
      { t: 10.6, type: 'block' },
      { t: 11.8, type: 'spike', count: 3 },
      { t: 13.3, type: 'spike', count: 3 },
      { t: 13.5, type: 'star', lift: 116 },
      { t: 16.0, type: 'checkpoint' },
      { t: 18.6, type: 'block' },
      { t: 19.75, type: 'spike', count: 2 },
      { t: 21.0, type: 'block' },
      { t: 22.15, type: 'spike', count: 2 },
      { t: 23.4, type: 'block' },
      { t: 24.55, type: 'spike', count: 2 },
      { t: 26.0, type: 'overhead' },
      { t: 26.7, type: 'spike', count: 3 },
      { t: 29.0, type: 'checkpoint' },
      { t: 31.5, type: 'spike', count: 2 },
      { t: 32.65, type: 'spike', count: 2 },
      { t: 33.8, type: 'spike', count: 2 },
      { t: 35.1, type: 'block' },
      { t: 36.4, type: 'overhead' },
      { t: 37.1, type: 'spike', count: 3 },
      { t: 38.5, type: 'block' },
      { t: 39.7, type: 'spike', count: 3 },
      { t: 40.05, type: 'star', lift: 42 },
      { t: 42.2, type: 'checkpoint' },
      { t: 44.6, type: 'overhead' },
      { t: 45.3, type: 'spike', count: 2 },
      { t: 46.6, type: 'block' },
      { t: 47.8, type: 'spike', count: 3 },
      { t: 49.3, type: 'overhead' },
      { t: 49.95, type: 'spike', count: 2 },
      { t: 51.3, type: 'spike', count: 2 },
      { t: 53.4, type: 'checkpoint' },
      { t: 55.8, type: 'block' },
      { t: 56.95, type: 'spike', count: 2 },
      { t: 58.2, type: 'block' },
      { t: 59.35, type: 'spike', count: 2 },
      { t: 60.7, type: 'overhead' },
      { t: 61.35, type: 'spike', count: 3 },
      { t: 63.2, type: 'block' },
      { t: 64.5, type: 'spike', count: 2 },
      { t: 66.2, type: 'checkpoint' },
      { t: 67.6, type: 'spike', count: 3 },
    ],
  },
  {
    id: 'level-5',
    name: '夜紫终章',
    speed: 348,
    duration: 68,
    palette: 4,
    script: [
      { t: 1.4, type: 'star', lift: 0 },
      { t: 3.2, type: 'spike', count: 2 },
      { t: 4.35, type: 'spike', count: 2 },
      { t: 5.6, type: 'block' },
      { t: 6.9, type: 'overhead' },
      { t: 7.55, type: 'spike', count: 2 },
      { t: 8.8, type: 'spike', count: 1 },
      { t: 10.1, type: 'spike', count: 3 },
      { t: 10.35, type: 'star', lift: 124 },
      { t: 12.2, type: 'block' },
      { t: 13.4, type: 'spike', count: 2 },
      { t: 15.2, type: 'checkpoint' },
      { t: 17.6, type: 'spike', count: 2 },
      { t: 18.75, type: 'spike', count: 2 },
      { t: 19.9, type: 'spike', count: 3 },
      { t: 21.4, type: 'overhead' },
      { t: 22.05, type: 'spike', count: 2 },
      { t: 23.3, type: 'block' },
      { t: 24.5, type: 'spike', count: 2 },
      { t: 25.8, type: 'overhead' },
      { t: 26.45, type: 'spike', count: 3 },
      { t: 28.2, type: 'checkpoint' },
      { t: 30.6, type: 'block' },
      { t: 31.75, type: 'spike', count: 2 },
      { t: 33.0, type: 'block' },
      { t: 34.15, type: 'spike', count: 2 },
      { t: 35.4, type: 'block' },
      { t: 36.55, type: 'spike', count: 2 },
      { t: 37.9, type: 'overhead' },
      { t: 38.55, type: 'spike', count: 2 },
      { t: 39.9, type: 'spike', count: 3 },
      { t: 40.2, type: 'star', lift: 38 },
      { t: 42.2, type: 'checkpoint' },
      { t: 44.6, type: 'spike', count: 3 },
      { t: 45.8, type: 'spike', count: 2 },
      { t: 47.1, type: 'overhead' },
      { t: 47.75, type: 'spike', count: 3 },
      { t: 49.2, type: 'block' },
      { t: 50.4, type: 'spike', count: 2 },
      { t: 51.6, type: 'spike', count: 2 },
      { t: 53.0, type: 'overhead' },
      { t: 53.65, type: 'spike', count: 2 },
      { t: 55.0, type: 'block' },
      { t: 56.2, type: 'spike', count: 3 },
      { t: 57.8, type: 'checkpoint' },
      { t: 60.0, type: 'overhead' },
      { t: 60.65, type: 'spike', count: 2 },
      { t: 61.9, type: 'block' },
      { t: 63.1, type: 'spike', count: 3 },
      { t: 64.5, type: 'overhead' },
      { t: 65.15, type: 'spike', count: 2 },
      { t: 66.2, type: 'spike', count: 1 },
    ],
  },
];
